### PR TITLE
Serbian translation

### PR DESCRIPTION
**Pull request by pejakm**

### CODE REVIEW

**Comment by k3b** [comment]
hello pejakm,

thanks for the translations.

please note that the app is still in a very early development-state and it is quite likely, that there will be a lot of changes in the qui until finished. thats why i have no german translations yet (my native language). I try to not rename the existing id-s ;-)

**Comment by pejakm** [comment]
No worries, I have it installed, and I'll keep translation up to date. :)

**Comment by k3b** [comment]
hello pejakm,

in 9 days i plan to release the next version of LocationMapViewer.

I donot think that the gui will change anymore till this release. i still have 

* two bugfixes in the queue 
* i need to do a lot documentation in the wiki
* i want to create a german translation.

If you like could you please add this missing translations. 

there should be only 18 new items below "    " in strings.xml

**Comment by pejakm** [comment]
Sure. I'll make a PR as soon as I can.

**Pull request merged**
